version: '3.8'

services:
  mongo:
    image: mongo:${MONGO_CONTAINER_TAG}
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - vol_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USUARIO}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_CREDENCIAL}

volumes:
  vol_mongo_data: 
