version: '3.8'

services:
  cassandra:
    image: cassandra:4.0
    container_name: ${CASSANDRA_CONTAINER_NAME}
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_DC=${CASSANDRA_DC}
      - CASSANDRA_RACK=${CASSANDRA_RACK}
      - CASSANDRA_SEEDS=${CASSANDRA_CONTAINER_NAME}
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra_data:/var/lib/cassandra
    ports:
      - "${CASSANDRA_PORT}:9042"
    networks:
      - database_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'
        reservations:
          cpus: '0.5'
          memory: '512M'
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ${MONGO_CONTAINER_NAME}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - database_net
    restart: unless-stopped

  postgis:
    image: postgis/postgis:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - database_net
    restart: unless-stopped

volumes:
  cassandra_data:
  mongo_data:
  postgis_data:

networks:
  database_net:
    driver: bridge
